### ISSUE TITLE
Phone numbers for departments should be human readable

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#189]
`+12135556003` => `(213) 555-6003`

**Comment by garnertb** [comment]
Should/can? we remove the validator that requires the +1 prefix?  Every phone number is in the US, and its confusing why the phone number shows up as invalid when saving.

**Comment by meilinger** [comment]
We could change the internal format of the phone number which I believe should take care of that, but it would be nice to have a method to automatically convert an incoming national format to international on save and simply render the phone number in the location dialect of the department.

**Comment by meilinger** [comment]
@HunterConnelly this might be a nice one to pick off when you get a chance

**Comment by garnertb** [comment]
@meilinger, @HunterConnelly 

Seems like there are three problems here:

1. When a FireDepartment is in the admin section (firecares.org/admin), the phone number must be international.  This is annoying because even if you edit a separate field the validator will tell you that the record's phone number is invalid.  I think this can be mitigated by adding a new setting: `PHONENUMBER_DEFAULT_REGION=US`.

2. When a phone number is displayed, it shows the raw phone number from the database which is sometimes national and sometimes international.  I think this can be mitigated by displaying the national version of the phone number `phonenumber.as_national` on the clientside (https://github.com/FireCARES/firecares/blob/master/firecares/firestation/templates/firestation/department_detail.html#L326).

3. Even when we display the nationalized numbers on the client side they aren't all that great XXX-XXX-XXXX.  Instead, it would be preferable to display as (XXX) XXX-XXXX.  This can be mitigated with a new template tag: https://docs.djangoproject.com/en/1.8/howto/custom-template-tags/#simple-tags.

For reference, I believe we are using this library to validate/store phone numbers: https://github.com/stefanfoulis/django-phonenumber-field.

**Comment by HunterConnelly** [comment]
@garnertb @meilinger #201 adds a manage.py command that formats phone and fax numbers stored in the db as XXXXXXXXXX to be formatted as human-readable on the client side.

**Comment by HunterConnelly** [comment]
@garnertb @meilinger #203 adds a filter to format phone numbers as (XXX) XXX-XXXX in department summaries.

**Comment by meilinger** [comment]
Looks good to me, thanks @HunterConnelly !  Closed via f8d91c6e26f01e5854ac2db1161253d6479e5b08
