### ISSUE TITLE
Include currently-selected hazard level in section headings

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#258]
_NOTE: apply to `public` branch_

- On department detail page include the current hazard level inline w/ "Community Risk Assessment", "Safe Grades" and "Annual Structure Fires" headings

**Comment by istodi** [comment]
Any ideas about a nice way to show it?

Maybe something like:
<img width="607" alt="captura de pantalla 2017-02-14 a la s 11 40 57" src="https://cloud.githubusercontent.com/assets/74675/22941271/7951b8c4-f2aa-11e6-8878-4ddbeb098b7f.png">

**Comment by meilinger** [comment]
i vote for something similar to the first option, but @cweinschenk what do you think?

**Comment by cweinschenk** [comment]
@meilinger @istodi I like the first one the best as well. Could the low risk text be bumped up a size or two and a little darker on the grey scale as well?

**Comment by istodi** [comment]
Sure, what about this
<img width="503" alt="captura de pantalla 2017-02-14 a la s 13 17 36" src="https://cloud.githubusercontent.com/assets/74675/22944931/00c93f68-f2b8-11e6-82d6-1d6f781207c2.png">

The current level selected is shown except for "all levels" since I found it a little redundant, what you think about it @cweinschenk?

**Comment by istodi** [comment]
#264

**Comment by cweinschenk** [comment]
I think that looks great.
