### ISSUE TITLE
Fix heatmap-associated graph axis rendering

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#261]
- On department detail page
- Axis appears to render upside down

Appears in:

IE: 11.576.14393, update 11.0.38
Microsoft Edge 38.14393.0.0

![image_png](https://cloud.githubusercontent.com/assets/197163/22904607/a5b925ee-f202-11e6-8c89-4356680dae40.jpg)

Should look like:

![community_assessment__washington_dc_fire___ems_department](https://cloud.githubusercontent.com/assets/197163/22904685/eb7c6fa0-f202-11e6-9247-edfc86472988.jpg)

**Comment by istodi** [comment]
The problem is an old issue with IE and css transformations for svg, is not fully supported but I've got the fix, nonetheless there is another visual bug in the aster chart when filtering data:

Before filter:
<img width="200" alt="captura de pantalla 2017-02-13 a la s 19 29 44" src="https://cloud.githubusercontent.com/assets/74675/22911010/41ed6824-f223-11e6-8f93-7084cd665966.png">
After filter:
<img width="200" alt="captura de pantalla 2017-02-13 a la s 19 30 21" src="https://cloud.githubusercontent.com/assets/74675/22911011/4572fab8-f223-11e6-830f-a0fd73392a2f.png">

Correct filtered view:
<img width="200" alt="captura de pantalla 2017-02-13 a la s 19 30 43" src="https://cloud.githubusercontent.com/assets/74675/22911013/477155e4-f223-11e6-9972-845dea491557.png">

**Comment by istodi** [comment]
#262 Fix the two issues, also removed the path-to-array-to-path helpers and instead used data binding.

**Comment by meilinger** [comment]
verified that things look good in IE11
