### ISSUE TITLE
InternalError at /departments/97668/settings/government-units

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#41]
I switched the filter to do an intersection vs a contains and I get the following error due to self intersecting polygons:

```
InternalError at /departments/97668/settings/government-units
GEOSIntersects: TopologyException: side location conflict at -104.81012499999991 40.710320000000081
```

**Comment by meilinger** [comment]
Root cause is quite a few invalid geoms across all of the USGS-prefixed tables.  In order to get this fixed, I'd need to run a ST_MakeValid (which would require altering geom to be MultiPolygon vs Polygon since many of the features have invalid rings that exist outside of the first ring), preliminary visual diff results look good and unfortunately area calculation diffs didn't help much since the original polys were bad.
